-- EJERCICIO 1

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Materiales')
DROP TABLE Materiales;

CREATE TABLE Materiales (
  Clave NUMERIC(5) NOT NULL,
  Descripcion VARCHAR(50),
  Costo NUMERIC(8,2)
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Proveedores')
DROP TABLE Proveedores;

CREATE TABLE Proveedores (
  RFC CHAR(13) NOT NULL,
  RazonSocial VARCHAR(50)
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Proyectos')
DROP TABLE Proyectos;

CREATE TABLE Proyectos (
  Numero  NUMERIC(5) NOT NULL,
  Denominacion VARCHAR(50)
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Entregan')
DROP TABLE Entregan;

CREATE TABLE Entregan (
  Clave NUMERIC(5) NOT NULL,
  RFC CHAR(13) NOT NULL,
  Numero NUMERIC(5) NOT NULL,
  Fecha DATETIME NOT NULL ,
  Cantidad NUMERIC(8,2)
);